name: monoidal-rows
version: 0.1.0.0

default-extensions:
  - LambdaCase
  - BlockArguments

  - ImportQualifiedPost

  - FlexibleInstances
  - UndecidableInstances
  - MultiParamTypeClasses

  - PatternSynonyms
  - ViewPatterns

  - TupleSections

  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable

ghc-options:
  - -Wall
  - -Wno-missing-signatures
  - -Wno-missing-pattern-synonym-signatures
  - -Wno-unused-top-binds

dependencies:
  - base
  - containers
  - bimap
  - mtl
  - hashable
  - data-default
  - template-haskell
  - pretty-simple
  - array

executables:
  monoidal_rows:
    main: Main.hs
    source-dirs: src
